// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Tree$PhyloLibWeb from "./tree.bs.js";

var dog = Tree$PhyloLibWeb.Tree.leaf_no_params("dog");

var cat = Tree$PhyloLibWeb.Tree.leaf_no_params("cat");

var mouse = Tree$PhyloLibWeb.Tree.leaf_no_params("mouse");

var dog_cat = Tree$PhyloLibWeb.Tree.zip_no_params(/* :: */[
      dog,
      /* :: */[
        cat,
        /* [] */0
      ]
    ]);

var dog_cat_mouse = Tree$PhyloLibWeb.Tree.zip_no_params(/* :: */[
      dog_cat,
      /* :: */[
        mouse,
        /* [] */0
      ]
    ]);

var z = Tree$PhyloLibWeb.Tree.zip_no_params(/* :: */[
      mouse,
      /* :: */[
        dog_cat,
        /* [] */0
      ]
    ]);

var SmallTree = {
  dog: dog,
  cat: cat,
  mouse: mouse,
  dog_cat: dog_cat,
  dog_cat_mouse: dog_cat_mouse,
  z: z
};

export {
  SmallTree ,
  
}
/* dog Not a pure module */
