// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Tree$PhyloLibWeb from "./tree.bs.js";

var dog = Tree$PhyloLibWeb.leaf_no_params("dog");

var cat = Tree$PhyloLibWeb.leaf_no_params("cat");

var mouse = Tree$PhyloLibWeb.leaf_no_params("mouse");

var dog_cat = Tree$PhyloLibWeb.zip_no_params({
      hd: dog,
      tl: {
        hd: cat,
        tl: /* [] */0
      }
    });

var dog_cat_mouse = Tree$PhyloLibWeb.zip_no_params({
      hd: dog_cat,
      tl: {
        hd: mouse,
        tl: /* [] */0
      }
    });

var z = Tree$PhyloLibWeb.zip_no_params({
      hd: mouse,
      tl: {
        hd: dog_cat,
        tl: /* [] */0
      }
    });

var SmallTree = {
  dog: dog,
  cat: cat,
  mouse: mouse,
  dog_cat: dog_cat,
  dog_cat_mouse: dog_cat_mouse,
  z: z
};

export {
  SmallTree ,
  
}
/* dog Not a pure module */
