const h3n2 = `
>H3N2 PB-2 Genome
agcgaaagcaggtcaaatatattcaatatggagagaataaaagaactaagagatttgatgtcgcagtctcgcactcgcga
gatactgacaaaaaccactgtggaccatatggccataatcaagaaatatacgtcaggaagacaggagaagaaccctgctc
ttaggatgaagtggatgatggcaatgaaatatccgattacagcagacaggaggataatggagatgatccctgaaagaaat
gagcaaggtcagactctttggagcaaaacgaatgatgctggatcagacagagtgatggtatcgcctctggctgtgacatg
gtggaatagaaatggaccaacgacaagtacagtccattatccgaaggtctacaaaacctactttgagaaggtcgaaaggt
taaagcatggaacctttggtcccgttcactttcggaatcaagttaaaatacgccgcagggttgacataaacccgggccac
gcagacctcagtgctaaagaagcacaagatgtcatcatggaggtcgttttcccaaacgaagtaggagccaggatattaac
atcagagtcacaattaacaataacaaaagaaaaaaaggaagagctccaagactgtaagattgctcctttgatggtggcat
acatgttggaaagagaattagttcgcaaaaccagattcctaccggtagctggtgggacaagcagcgtgtatatcgaggtg
ttgcacttgacccaggggacctgccgggaacaaatgtatacaccgggaggagaggtgagaaatgatgatattgatcagag
tttaattattgctgctagaaatattgtcagaagagcaacagtatcagcagatccattagcttcgctcttggaaatgtgcc
atagcacacaaattggtggaataaggatggtagatattcttaggcaaaatccaacagaagagcaagctgtggatatatgc
aaagcagcaatgggtctgaggatcagttcatccttcagctttggaggtttcactttcaaaaggacaagtggatcatctgt
caaaagagaagaagaagtactcacaggcaaccttcagacattgaaaataagagtgcacgaaggatatgaggaatttacaa
tggtagggcgaagagcaacagccattttaaggaaagcaaccagaaggctgattcaattaatagtgagtggaagagacgag
caatcaattgccgaagcaatcatagtggcaatggtgttctcacaagaggattgcatgataaaggcagtccgaggcgattt
gaattttgtcaacagagcgaaccagcggctgaatcctatgcatcaactcctgaggcacttccagaaggatgcaaaggtgc
tatttcaaaactggggagttgaacccattgacaatgtcatggggatgatcggaatattacctgacatgacccccagcaca
gaaatgtcactaaggggagtaagggtcagtaaaatgggagtggatgaatattccagtactgagagagtggtgtgagcat
tgaccgtttcttgagggtccgagaccagaggggaaatgtgctcttgtctcctgaagaagttagtgaaacacagggaacag
aaaagctgacaataacatattcatcgtccatgatgtgggaaatcaatggcccggaatcagtgctggtcaacacatatcag
tggatcattagaaactgggaaactgtgaagatccagtggtcccaagaccctacaatgctatacaataagatgaaatttga
gccttttcaatctttagtgcctaaggctgccagaggccagtatagcggctttgtgaggacgctatttcagcaaatgcgtg
atgtgctgggaacatttgacactgtccagataataaagctactaccatttgcagcagccccgccagaacagagtagaatg
cagttctcttctctaactgtgaacgtaaggggttcaggaatgagaatacttgtgagaggtaattctcctgtgttcaatta
taacaaggcaaccaagaggctcacaatccttggaaaggacgcaggtgcactgactgaagatccagatgaaggaacagcag
gagtggagtctgcagtattaagaggatttctaattctgggcaaagaagacaaaagatatggaccagcattgagcatcaac
gaattgagcaatcttgcgaaaggggagaaggctaatgtgttgatagggcaaggagacgtggtgttggtaatgaaacggaa
acgggactctagcatacttactgacagccagacagcgaccaaaagaattcggatggccatcaattagtgtcgaattgttt
aaaaacgaccttgtttctact
`

export default h3n2;
